# Generated by Django 2.0.2 on 2018-05-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestReserv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='Special_Accomidations',
            new_name='Special_Accommodations',
        ),
        migrations.AlterField(
            model_name='request',
            name='tour_time',
            field=models.IntegerField(choices=[(9, '9:00am-10:00am'), (10, '10:00am-11:00am'), (11, '11:00am-12:00pm'), (12, '12:00pm-1:00pm'), (13, '1:00pm-2:00pm'), (14, '2:00pm-3:00pm'), (15, '3:00pm-4:00pm')]),
        ),
    ]
